services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: sci_summ_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_HOST_AUTH_METHOD: trust  # Разрешаем подключения без пароля для локальной разработки
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sci_summ_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  